package exceptions

internal class PoisonPillException : RuntimeException("Thread finished due to PoisonPill")